Update action.yml for Helm packaging and pushing

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -97,7 +97,16 @@ runs:
       - name: Empaquetar y subir Helm chart a Huawei SWR
         shell: bash
         run: |
-          export HELM_EXPERIMENTAL_OCI=1
           helm package --version ${{ inputs.helmChartVersionLatest }} --app-version ${{ inputs.appVersion }} --namespace ${{ inputs.namespace }} .
-          echo "${{ inputs.SWR_PASSWORD }}" | helm registry login ${{ inputs.SWR_URL }} --username "${{ inputs.SWR_USERNAME }}" --password-stdin
-          helm push ${{ inputs.teamProject }}-${{ inputs.appName }}-${{ inputs.helmChartVersionLatest }}.tgz oci://${{ inputs.SWR_URL }}/helm
+
+          CHART_FILE="${{ inputs.teamProject }}-${{ inputs.appName }}-${{ inputs.helmChartVersionLatest }}.tgz"
+
+          STATUS=$(curl -s -o /tmp/helm_resp.json -w "%{http_code}" -X POST "https://${{ inputs.SWR_URL }}/helm" -u "${{ inputs.SWR_USERNAME }}:${{ inputs.SWR_PASSWORD }}" -F "chart=@${CHART_FILE}")
+
+          echo "Status: $STATUS"
+          cat /tmp/helm_resp.json
+
+          if [[ "$STATUS" != "201" && "$STATUS" != "200" ]]; then
+            echo "Error al subir el Helm chart"
+            exit 1
+          fi
