Nueva Action de Sync Argo (Copiado de la vieja)
Copiado de https://github.com/infrastructure-services/actions/tree/sync-argo

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,103 +1,207 @@
-name: 'Build and Deploy'
-description: 'Unique step to Build and Deploy'
+name: 'Sincronizacion de ArgoCD'
+
 inputs:
-  # ACR
   ACR_USERNAME:
     description: "user de acr"
     required: true
+    default: ''
   ACR_PASSWORD:
     description: "passwrd de acr"
     required: true
+    default: ''
   ACR_NAME:
     description: "nommbre del acr"
     required: true
+    default: ''
   ACR_FULL_NAME:
     description: "nombre del acr con azurecr.io"
     required: true
-
-  # App
+    default: ''
   appName:
     description: "Nombre de la aplicacion (dentro del proyecto)"
     required: true
+    default: orleans-grain
   teamProject:
     description: "Nombre del proyecto/equipo"
     required: true
+    default: qa
   appVersion:
     description: "tag para subir imagen"
     required: true
-  matrix_deploy:
-    description: "deploy en multiples ambientes"
-    required: false
-    default: "[]"
-  # Values
-  github_token:
-    description: "Token para descargar el codigo de templates HELM"
+    default: latest
+  ARGO_USERNAME:
+    description: "usuario de ARgocd"
     required: true
+  ARGO_PASSWORD:
+    description: "pass de ARgocd"
+    required: true
+  ARGO_URL:
+    description: "url de ARgocd"
+    required: true
+  helmChartVersionLatest:
+    description: "VersionHelm"
+    required: true
+  namespace:
+    description: "nombre de namespaces"
+    required: false
+    default: ""
+  environment:
+    description: "nombre de namespaces"
+    required: false
+    default: ""
+#env:
+  #Es un valor que viene del secreto, pero el install de helm lo espera cmo variable 'plana'
+#  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 runs:
   using: "composite"
   steps:
-    - name: Checkout
-      uses: actions/checkout@v3.5.0
-      with:
-        fetch-depth: 0
+      - run: echo hi!, we working.
+        shell: bash
+      - run: ls
+        shell: bash
+###REVISAR SI ESTO YA ESTA DE LA EJECUCION ANTERIOR
 
-    - name: Login to Azure Container Registry
-      uses: azure/docker-login@v1
-      with:
-        login-server: ${{ inputs.ACR_NAME }}.azurecr.io 
-        username: ${{ inputs.ACR_USERNAME }}
-        password: ${{ inputs.ACR_PASSWORD }}
+      - name: Generate name
+        shell: bash
+        id: name
+        run: echo "applicationName=${{inputs.teamProject}}-${{inputs.appName}}-${{inputs.environment}}" >> $GITHUB_OUTPUT
 
-    - name: Get the branch name
-      id: branch
-      run: echo "BranchName=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
-      shell: bash
+      - uses: actions/download-artifact@v3
+        with:
+          name: ${{inputs.appName}}-${{inputs.namespace}}
+          
 
-    - name: Use the branch name
-      id: semanticBranches
-      run: | 
-        echo "The branch name is ${{ steps.branch.outputs.BranchName }}"
-        if [[ ${{ steps.branch.outputs.BranchName }} == "main" ]]; then
-          echo "configureBranch=[\"main\"]" >> $GITHUB_OUTPUT
-        else
-          echo "configureBranch=[\"main\", {\"name\": \"${{ steps.branch.outputs.BranchName }}\", \"prerelease\": \"${{ steps.branch.outputs.BranchName }}\" }]" >> $GITHUB_OUTPUT
-        fi
-      shell: bash
-        
-    - name: "Generate Release"
-      id: version
-      uses: architecture-it/actions@next-version
-      with:
-        github_token: ${{ inputs.github_token }}
-        only_version: 'false'
-        branches: ${{ steps.semanticBranches.outputs.configureBranch }}
-
-    - name: "Pull-Tag-Push imagen"
-      if: steps.version.outputs.new-version != ''
-      id: pullImage
-      run: |
-        echo "Pull imagen"
-        echo "::notice::Version Latest: ${{ steps.version.outputs.new-version }}"
-
-        IFS=',' read -r -a deployments <<< "${{ inputs.matrix_deploy }}"
-        # Limpia y prepara el array de aplicaciones
-        deployments=($(for deployment in "${deployments[@]}"; do echo "$deployment" | xargs | sed 's/[][]//g'; done))
-        
-        if [ ${#deployments[@]} -eq 0 ]; then
-          # Ejecuta los comandos una sola vez si no hay aplicaciones especificadas
-          docker pull ${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}:${{ inputs.appVersion}}
-          docker tag ${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}:${{ inputs.appVersion}} ${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}:${{ steps.version.outputs.new-version }}
-          docker push ${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}:${{ steps.version.outputs.new-version }}
-          echo "::notice::Image name: ${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}:${{ steps.version.outputs.new-version }}"
-        else
-          # Ejecuta los comandos para cada aplicación si hay aplicaciones especificadas
-          for deployment in "${deployments[@]}"; do
-            docker pull ${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}-$deployment:${{ inputs.appVersion}}
-            docker tag ${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}-$deployment:${{ inputs.appVersion}} ${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}-$deployment:${{ steps.version.outputs.new-version }}
-            docker push ${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}-$deployment:${{ steps.version.outputs.new-version }}
-            echo "::notice::Image name: ${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}-$deployment:${{ steps.version.outputs.new-version }}"
+        # Se intenta 10 veces todos los pasos, con un sleep 20
+      - name: Login ArgoCD
+        shell: bash
+        run: |-
+          echo '${{ inputs.ACR_PASSWORD }}' | helm registry login ${{ inputs.ACR_FULL_NAME }} --username ${{ inputs.ACR_USERNAME }} --password-stdin
+          #cp poc-manifiestos-main/values.yaml .
+          #cp poc-manifiestos-main/Chart.yaml .
+          
+          echo 'login a argocd'
+          variableOk=0
+          argoCommand="argocd login --username ${{ inputs.ARGO_USERNAME }} --password ${{ inputs.ARGO_PASSWORD }} --insecure ${{ inputs.ARGO_URL }} --grpc-web"
+          for i in {1..5}
+          do
+          if eval "$argoCommand"; then
+              echo "ArgoCD login OK"
+              variableOk=1
+              break
+             else
+               echo "ArgoCD login $i/5"
+               sleep 40
+             fi
           done
-        fi
-      shell: bash
-    - run: echo "✅ Success"
-      shell: bash
+          if [[ $variableOk != "1" ]]
+          then
+              echo "Error en ArgoCD Login" >&2;
+              exit 1
+          fi
+
+      - name: Create Project
+        shell: bash
+        run: |
+          echo 'creacion proyecto argocd'
+          variableOk=0
+          argoCommand="argocd proj create ${{inputs.namespace}} --upsert --dest https://kubernetes.default.svc,${{inputs.namespace}} --src  ${{ inputs.ACR_FULL_NAME }}/helm --grpc-web"
+          
+          for i in {1..5}
+          do
+          if eval "$argoCommand"; then
+              echo "ArgoCD Project create OK"
+              variableOk=1
+              break
+             else
+               echo "ArgoCD Project create $i/5"
+               sleep 40
+             fi
+          done
+          if [[ $variableOk != "1" ]]
+          then
+              echo "Error en ArgoCD Project create" >&2;
+              exit 1
+          fi
+      - name: creación app ArgoCD
+        shell: bash
+        run: |
+          echo 'creacion app argocd'
+          variableOk=0
+          argoCommand="argocd app create ${{ steps.name.outputs.applicationName }} --repo ${{ inputs.ACR_FULL_NAME }}/helm --helm-chart ${{inputs.teamProject}}-${{inputs.appName}} --upsert --helm-set Chart.yaml=Chart.yaml --helm-set-file values.yaml=values.yaml --helm-set-file Chart.yaml=Chart.yaml --revision ${{ inputs.helmChartVersionLatest}} --dest-namespace ${{inputs.namespace}} --dest-server https://kubernetes.default.svc --sync-policy auto --auto-prune --self-heal --project ${{inputs.namespace}} --grpc-web"
+          
+          for i in {1..5}
+          do
+          if eval "$argoCommand"; then
+              echo "ArgoCD app create OK"
+              variableOk=1
+              break
+             else
+               echo "ArgoCD app create $i/5"
+               sleep 40
+             fi
+          done
+          if [[ $variableOk != "1" ]]
+          then
+              echo "Error en ArgoCD app create" >&2;
+              exit 1
+          fi
+      - name: Wait Sync
+        shell: bash
+        run: |
+          #Wait. Espera la synchronizacion, esperan 40s, esperan 3 veces
+          # validar el nombre, antes tenia el -qa al final
+          argoWait="argocd app wait ${{ steps.name.outputs.applicationName }} --health --operation --timeout 30"
+          for i in {1..3}
+          do
+          if eval "$argoWait"; then
+                echo "ArgoCD app wait OK"
+                break
+            else
+                echo "ArgoCD app wait $i/5"
+                sleep 40
+            fi
+          done
+      - name: Clear cache
+        shell: bash
+        run: |
+          #Limpia cache de argocd - hard refresh
+          argocd app get ${{ steps.name.outputs.applicationName }} refresh --hard-refresh --grpc-web 2>&1
+          
+      - name: Sync
+        shell: bash
+        run: |
+          #Synch del repo (Fuerza el cambio de la aplicación a lo que se encuentra en los repos)
+          argoCommand="argocd app sync ${{ steps.name.outputs.applicationName }} --prune --force --retry-limit 5 --grpc-web --async"
+          variableOk=0
+          for i in {1..5}
+          do
+          if eval "$argoCommand"; then
+              echo "ArgoCD sync OK"
+              variableOk=1
+              break
+             else
+               echo "ArgoCD sync $i/5"
+               sleep 40
+             fi
+          done
+          if [[ $variableOk != "1" ]]
+          then
+              echo "Error en ArgoCD sync" >&2;
+              exit 1
+          fi
+
+      - name: Wait Sync
+        shell: bash
+        run: |
+          #Wait. Espera la synchronizacion, esperan 40s, esperan 3 veces
+          argoWait="argocd app wait ${{ steps.name.outputs.applicationName }} --health --operation --timeout 30"
+          for i in {1..3}
+          do
+          if eval "$argoWait"; then
+                echo "ArgoCD app wait OK"
+                break
+            else
+                echo "ArgoCD app wait $i/5"
+                sleep 40
+            fi
+          done
