Adapto a nuevos inputs

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -26,46 +26,56 @@ inputs:
 runs:
   using: "composite"
   steps:
-      - run: echo 'Inicia el proceso'
-        shell: bash
+    - run: echo 'Inicia el proceso'
+      shell: bash
       
-      - name: Install Helm
-        uses: azure/setup-helm@v3
-        with:
-          version: v3.12.3 #Helm 13 tiene un bug
-      
-      - name: Reviso archivos y version helm
-        shell: bash
-        run: |-
-           ls
-           helm version --short
+    - name: Install Helm
+      uses: azure/setup-helm@v5
+      with:
+        version: v3.21.2 #Anteriormente 3.12.3
+    
+    - uses: actions/download-artifact@v6
+      with:
+        name: ${{inputs.appName}}-${{inputs.namespace}}
 
-      - uses: actions/download-artifact@v4
-        with:
-          name: ${{inputs.appName}}-${{inputs.namespace}}
-
-    # Verifica helm por errores (deberia ser bloqueante). Revisar este paso con un Json para asegurar que esté correcto.
-      - name: Helm Lint 
-        shell: bash
-        run: |-
-          helmLint="helm lint --values=values.yaml > /dev/null 2>&1"
-          if eval "$helmLint"; then
-             echo "HELM Lint OK - The template folder and values file format is OK";
-          else
-             echo "HELM Lint FAIL - There is a problem with the folder 'templates' or the values file format";
-             exit 1
-          fi
-
-      - name: Login to Azure Container Registry
-        uses: azure/docker-login@v1
-        with:
-          login-server: ${{ inputs.ACR_NAME }}.azurecr.io #ACR_FULL_NAME incluye el azurecr.io
-          username: ${{ inputs.ACR_USERNAME }}
-          password: ${{ inputs.ACR_PASSWORD }}
-      - name: Enpaquetar y subir helm a acr
-        shell: bash
-        run: |-
-          export HELM_EXPERIMENTAL_OCI=1 #Es necesario para el chart save}}
-          helm package --version ${{ inputs.helmChartVersionLatest}} --app-version ${{ inputs.appVersion}} --namespace ${{ inputs.namespace}} .
-          echo '${{ inputs.ACR_PASSWORD }}' | helm registry login ${{ inputs.ACR_FULL_NAME}} --username ${{ inputs.ACR_USERNAME}} --password-stdin
-          helm push ${{inputs.TeamProject}}-${{inputs.appName }}-${{inputs.helmChartVersionLatest}}.tgz  oci://${{inputs.ACR_FULL_NAME }}/helm/ # ${{ inputs.TeamProject}}-${{ inputs.appName}}  # :${{ env.helmChartVersionLatest}}
+  # Verifica chart por errores de manifiesto. 
+  # La funcionalidad de este paso se puede ampliar mediante un JSON de configuración.
+    - name: Helm Lint 
+      shell: bash
+      run: |-
+        helmLint="helm lint --values=values.yaml > /dev/null 2>&1"
+        if eval "$helmLint"; then
+           echo "HELM Lint OK - El formato del chart y los values parece correcto";
+        else
+           echo "HELM Lint FAIL - El formato de chart y/o el archivo values parecen ser incorrectos";
+           helm lint --values=values.yaml
+           exit 1
+        fi
+    - name: Preparación de variables de configuración 
+      shell: bash
+      run: |-
+        APP_NAME=$(echo "$appdataJson" | jq -r '.appdata.appname')
+        PROJECT_NAME=$(echo "$appdataJson" | jq -r '.appdata.projectName')
+        CHART_NAME="${PROJECT_NAME}-${APP_NAME}"
+        NAMESPACE="${PROJECT_NAME}-${{inputs.sufijo}}"
+        echo "Obtenido nombre de app: ${APP_NAME}"
+        echo "Obtenido proyecto: ${PROJECT_NAME}"
+        echo "Obtenido chart-name: ${CHART_NAME}"
+        echo "Obtenido namespace: ${NAMESPACE}"
+        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
+        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
+        echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
+        echo "CHART_NAME=$CHART_NAME" >> $GITHUB_ENV
+    - name: Login to Azure Container Registry
+      uses: azure/docker-login@v2
+      with:
+        login-server: ${{ inputs.ACR_FULL_NAME }}
+        username: ${{ inputs.ACR_USERNAME }}
+        password: ${{ inputs.ACR_PASSWORD }}
+    - name: Empaquetar y subir helm chart a acr
+      shell: bash
+      run: |-
+        export HELM_EXPERIMENTAL_OCI=1 #Es necesario para el chart save}}
+        helm package --version ${{ inputs.helmChartVersionLatest}} --app-version ${{ inputs.appVersion}} --namespace ${{ env.NAMESPACE}} .
+        echo '${{ inputs.ACR_PASSWORD }}' | helm registry login ${{ inputs.ACR_FULL_NAME}} --username ${{ inputs.ACR_USERNAME}} --password-stdin
+        helm push ${{env.CHART_NAME}}-${{inputs.helmChartVersionLatest}}.tgz  oci://${{inputs.ACR_FULL_NAME }}/helm/ # ${{env.CHART_NAME}}  # :${{ env.helmChartVersionLatest}}
